version: "3.9"

services:
  app:
    build:
      context: "./context"
      dockerfile: "Dockerfile"
      args:
        LANG: "${LANG:-en_US.UTF-8}"
        TZ: "${TIMEZONE:-UTC}"
    ports:
      - "80:80"
    networks:
      - "app"
    environment:
      TERM: "${TERM}"
      ZSH_THEME: "${ZSH_THEME}"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

networks:
  app:
    name: "${APP_NAME}"
